# These are supported funding model platforms

github: [beyrakIn] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [beyrakIn, dashgin]
patreon: beyrak # Replace with a single Patreon username
#open_collective: beyrakIn # Replace with a single Open Collective username
#ko_fi: beyrakIn # Replace with a single Ko-fi username
#tidelift: http://beyrak.me/ # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: Filmio  # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: beyrakIn # Replace with a single Liberapay username
#issuehunt: beyrakIn # Replace with a single IssueHunt username
#otechie: beyrakIn # Replace with a single Otechie username
custom: ['http://beyrak.me/'] # Replace with up to 4 custom sponsorship URLs e.g., ['http://beyrak.me/', 'http://beyrak.me/']
